// <auto-generated />
using Assignment_4_Movies.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebDevApplication.Migrations
{
    [DbContext(typeof(StudentFormContext))]
    [Migration("20220128003954_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Assignment_4_Movies.Models.StudentModel", b =>
                {
                    b.Property<int>("student_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("street_address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("zip")
                        .HasColumnType("INTEGER");

                    b.HasKey("student_id");

                    b.ToTable("StudentModel");

                    b.HasData(
                        new
                        {
                            student_id = 1,
                            category = "full_time",
                            city = "South Jordan",
                            email = "test@test.com",
                            first_name = "Spencer",
                            last_name = "Harrison",
                            phone_number = "801-915-7986",
                            state = "UT",
                            street_address = "1466 W 11150 S",
                            zip = 84095
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
