// <auto-generated />
using Assignment_4_Movies.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment_4_Movies.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    [Migration("20220125060626_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Assignment_4_Movies.Models.MovieModel", b =>
                {
                    b.Property<int>("movid_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent_to")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("movid_id");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            movid_id = 1,
                            category = "Comedy",
                            director = "Smartest Man",
                            edited = false,
                            lent_to = "",
                            notes = "",
                            rating = "PG",
                            title = "Hot Rod",
                            year = 2000
                        },
                        new
                        {
                            movid_id = 2,
                            category = "Rom/Com",
                            director = "Cute Girl",
                            edited = true,
                            lent_to = "",
                            notes = "",
                            rating = "G",
                            title = "13 Going On 30",
                            year = 2002
                        },
                        new
                        {
                            movid_id = 3,
                            category = "Action",
                            director = "Russo Brothers",
                            edited = false,
                            lent_to = "",
                            notes = "",
                            rating = "PG",
                            title = "SpiderMan No Way Home",
                            year = 2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
